Blog/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using System.Text;

namespace Blog.Controllers
{
    public class ArticlesController : Controller
    {
        private BlogsContext db = new BlogsContext();

        // GET: Articles
        public ActionResult Index()
        {
            var articles = db.Articles.Include(a => a.Categories).Include(a => a.Utilisateurs);
            return View(articles.ToList());
        }

        // GET: Articles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }

        // GET: Articles/Create
        public ActionResult Create()
        {
            ViewBag.idCategorie = new SelectList(db.Categories, "idCategorie", "Libelle");
            ViewBag.idUtilisateur = new SelectList(db.Utilisateurs, "IdUtilisateur", "prenom");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idArticle,idUtilisateur,idCategorie,titre,contenu,datePublication")] Articles articles)
        {
            StringBuilder sbContenu = new StringBuilder();
            sbContenu.Append(HttpUtility.HtmlEncode(articles.contenu));
            if (ModelState.IsValid)
            {
                db.Articles.Add(articles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCategorie = new SelectList(db.Categories, "idCategorie", "Libelle", articles.idCategorie);
            ViewBag.idUtilisateur = new SelectList(db.Utilisateurs, "IdUtilisateur", "prenom", articles.idUtilisateur);
            return View(articles);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategorie = new SelectList(db.Categories, "idCategorie", "Libelle", articles.idCategorie);
            ViewBag.idUtilisateur = new SelectList(db.Utilisateurs, "IdUtilisateur", "prenom", articles.idUtilisateur);
            return View(articles);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idArticle,idUtilisateur,idCategorie,titre,contenu,datePublication")] Articles articles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCategorie = new SelectList(db.Categories, "idCategorie", "Libelle", articles.idCategorie);
            ViewBag.idUtilisateur = new SelectList(db.Utilisateurs, "IdUtilisateur", "prenom", articles.idUtilisateur);
            return View(articles);
        }

        // GET: Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articles articles = db.Articles.Find(id);
            db.Articles.Remove(articles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        //[Authorize]
        public ActionResult AjouterCommentaire()
        {
            return PartialView("PartialAjoutCommentaire");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Controllers/CategoriesController.cs
using Blog.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class CategoriesController : Controller
    {
        //BlogsContext db = new BlogsContext();

        private readonly IContext db;

        public CategoriesController()
        {
            db = new BlogsContext();
        }
        public CategoriesController(IContext context)
        {
            db = context;
        }

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());            
        }


        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index", "Categories");

            }
            
           Categories categ = db.Categories.Find(id);
            if (categ == null)
            {
                return HttpNotFound();
            }
            return View(categ);
        }
        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Creer(Categories categ)
        {
            db.Categories.Add(categ);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Categories categories)
        {         

            if (ModelState.IsValid)
            {
                db.Categories.Add(categories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categories);
        }
        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idCategorie,Libelle")] Categories categories)
        {
            if (ModelState.IsValid)
            {               
                //db.Entry(categories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categories);
        }

        // GET: Categories/Total articles
        public int GetTotalArticle(int id)
        {            
            int TotalArticle = db.Articles.Where(x => x.idCategorie == id).Count();

            return TotalArticle;
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = db.Categories.Find(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            if ((GetTotalArticle((int)id) != 0))
            {
                return new ContentResult
                {
                    Content = "Impossible d'effectuer la suppression, car cette catégorie contient des articles !!!!"
                };
            }
            return View(categories);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categories categories = db.Categories.Find(id);
            db.Categories.Remove(categories);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
              // db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


    
}

Blog/Views/Categories/Create.cshtml
@model Blog.Models.Categories

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categories</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste des catégories", "Index")
</div>

Blog/Views/Categories/Delete.cshtml
@model Blog.Models.Categories

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Êtes-vous sûr de vouloir supprimer cette catégorie ?</h3>
<div>
    <h4>Categories</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste des catégories", "Index")
        </div>
    }
</div>

Blog/Views/Categories/Details.cshtml
@model Blog.Models.Categories

@{
    ViewBag.Title = "Catégorie";
}

<h2>Details</h2>

<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.idCategorie }) |
    @Html.ActionLink("Retour à la liste des catégories", "Index")
</p>

Blog/Views/Categories/Edit.cshtml
@model Blog.Models.Categories

@{
    ViewBag.Title = "Modifier une catégorie";
}

<h2>Modifier une catégorie</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idCategorie)

        <div class="form-group">
            @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modifier" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste des catégories", "Index")
</div>

Blog/Views/Categories/Index.cshtml
@model IEnumerable<Blog.Models.Categories>

@{
    ViewBag.Title = "Index";
}

<h2 style="padding:10px;">La liste des catégories</h2>

<p class="text-info h4" style="padding-top:30px; padding-bottom:30px;">
    <span class="glyphicon glyphicon-list-alt"></span> @Html.ActionLink("Ajouter une nouvelle catégorie", "Create") | @Html.ActionLink("Liste des articles", "Index", "Articles")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
        <th align="center">Nombre total d'articles</th>
        <th align="center">Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Libelle)
        </td>
        <td style="padding-left:60px;">           
            @Html.Action("GetTotalArticle", new { id = item.idCategorie })
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id=item.idCategorie }) |
            @Html.ActionLink("Details", "Details", new { id=item.idCategorie }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.idCategorie })
        </td>
    </tr>
}

</table>